### PR TITLE
Up down

### PR DESCRIPTION
**Pull request by jerome-cirrios**
new functionality to reorder the names

### CODE REVIEW

**Comment by rnicholus** [comment]
and this is...?

**Comment by jerome-cirrios** [comment]
new fonctionnality to reorder the names

**Comment by rnicholus** [comment]
Ah, I see. Cool! Instead of merging this into the edit-names branch, can you put this on a new branch?

**Comment by jerome-cirrios** [comment]
Not sure how to do that. I can't select a new branch when i send the pull the request.

**Comment by rnicholus** [comment]
You'll want to base your PR off of master, and I can then merge it into a new branch.

**Pull request closed without merging**
