### PR TITLE
running test improvements: use single test command "npm test"

### PR DESCRIPTION
**Pull request by daggerok**
hi,
i little bit simplified testing.
tested on latest osx

### CODE REVIEW

**Comment by rnicholus** [comment]
Thanks for the PR, but I'm not seeing how this is "simplified". Instead, it looks quite a bit more complex. What specific goal(s) did you have that prompted these changes? Also, the build is now failing, and I'm not certain what the cause is.

**Comment by daggerok** [comment]
Yeah, I saw build is fail. Simplify means using: install selenium, start server, run test, stop..

**Comment by rnicholus** [comment]
Sorry, how is that easier than:

1. `npm start`
2. `npm run start-webdriver`
3. `npm test`

...not to mention the large number of new npm scripts you introduced?

**Comment by daggerok** [comment]
just, nam test

and you also have to stop server/webdriver (so it’s 4 and 5)

**Pull request closed without merging**
