### PR TITLE
Reorder Names

### PR DESCRIPTION
**Pull request by skvale**
I based this off of Pull Request #6 Up-Down by [jerome-cirrios](https://github.com/jerome-cirrios/fullstack-react/tree/up-down)

Which is based off of the edit-names branch

I believe it is a bit simpler to treat a name's position in data.names as the id.

The main part is using swap in the server 
```javascript
+            route: 'names.swap',
+            call: (callPath, args) => {
+                var nameId1 = args[0];
+                var nameId2 = args[1];
+                if(nameId2 < 0 || nameId2 >= data.names.length) {
+                    return {path: ['names', 'length'], value: data.names.length}
+                }
+                var tmpName = data.names[nameId1].name;
+                data.names[nameId1].name = data.names[nameId2].name
+                data.names[nameId2].name = tmpName
+                return [
+                    {
+                        path: ['names', nameId1, 'name'],
+                        value: data.names[nameId1].name
+                    },
+                    {
+                        path: ['names', nameId2, 'name'],
+                        value: data.names[nameId2].name
+                    }
+                ]
+            }
```

Which is called by these events

```javascript
+    handleUpClick(event) {
+        event.preventDefault()
+        model.call(['names','swap'],[this.props.idx, parseInt(this.props.idx)-1],['names'])
+            .then(() => {
+                this.props.update()
+            })
+    }
+    
+    handleDownClick(event) {
+        event.preventDefault()
+        model.call(['names','swap'],[this.props.idx, parseInt(this.props.idx)+1],['names'])
+            .then(() => {
+                this.props.update()
+            })
+    }
```

I put together a running example on [heroku](http://fullstack-react-example.herokuapp.com/)

### CODE REVIEW

**Comment by skvale** [comment]
Perhaps this isn't the right approach though, 

Referencing this [falcor issue](https://github.com/Netflix/falcor/issues/585)
>I don't really want to swap two items based on index, in case the model maintained on the server has changed. Instead, I just want to swap those two records.

**Comment by rnicholus** [comment]
Thanks Sam. In your router code, I'm seeing several references to "IDs", but the name records don't actually have IDs in their current form, just indexes. 

Regarding the referenced issue, thanks for reminding me. I need to follow-up with a couple issues I've opened in the Falcor repository.

**Comment by skvale** [comment]
Updated to use `idx`.
Feel free to close this and use #6. 
I was just curious about using an `index` vs. an `id` for swapping.

**Comment by rnicholus** [comment]
In order to reference records explicitly by index client-side, and then have that automagically translated into the correct record using its known ID, you'll need to return a reference to the ID record/route when your Falcor server responds to a request for the records by index.

**Pull request closed without merging**
